### ISSUE TITLE
Drag and Drop in page manager

### ISSUE THREAD

**Issue by creisi23** [gtbu/Typesetter-5.3-p8#10]
It seems, that it's not possible to drag and drop pages in Page Manager. The console says: Uncaught TypeError: this.dragDirection is undefined.

**Comment by creisi23** [comment]
A more detailed error message:
Uncaught TypeError: this.dragDirection is undefined
    jQuery 3
        _intersectsWithPointer
        prop
        prop
    _mouseDrag https://example.com/include/thirdparty/js/nestedSortable.js?v=5.3-p8 b3:89
    jQuery 10
        prop
        _mouseStart
        prop
        prop
        _mouseMove
        prop
        prop
        _mouseMoveDelegate
        dispatch
        handle

**Comment by gtbu** [comment]
Sorry - i have no problems with that ( with js-minimisation and addition - both on or off ) - is there perhaps a Javascript blocker active . Which browser - i testet with newest Firefox and Edge and php8.0

**Comment by creisi23** [comment]
Have tested it with Firefox, Chromium and Palemoon under localhost on a linux system and in the web on different hosting providers. Didn't work with all combinations.

**Comment by gtbu** [comment]
I tested all versions of nested-sortable with the same result . 
I must first make in TP5.2 installation in the web - under xampp and Tp5.3 or Tp 5.3 everything functions.

**Comment by gtbu** [comment]
Replacement of nestedSortable.js version 1.34 against version 2.1a solves the problem. In this newest version this.dragDirection is used.
