### ISSUE TITLE
Edit Layout (/Admin_Theme_Content/Edit/default)

### ISSUE THREAD

**Issue by rifloom** [gtbu/Typesetter-5.3-p8#17]
'handlers' => array() in Typesetter  (_data/sites/pages.php) does not work like Typesetter 5.2 PHP7

Default template used (Bootstrap 4/footer)

If you go to the "Edit Layout" admin page and add, for example, to the area "Footer Column 1" Extracontent -> Lorem
The content ("Footer Column 1") disappears from the page, it is not shown?! The same happens with all containers ... its contents are not replaceable!

      'handlers' => 
      array (
        'RXh0cmE6Rm9vdGVyX0NvbA_0' => 
        array (
          0 => 'Extra:Lorem',
          1 => 'Extra:Footer_Column_1',
        ),
      ),

RXh0cmE6Rm9vdGVyX0NvbA = Extra:Footer_Col

If you add something to an empty container, you get an error message "Oops, that didn't work, please try again. (Not found in container)"
Or it says "saved" but nothing is visible on the page.

      'handlers' => 
      array (
        'QWZ0ZXJDb250ZW50Og_0' => 
        array (
          0 => 'Extra:Lorem',
        ),
      ),
QWZ0ZXJDb250ZW50Og = AfterContent:

When you leave the page, you will occasionally receive a message "Leave site? Changes you made may not be saved."

________________________
PS! ith my plugin (https://www.typesettercms.com/Plugins/372_Rif_MenuFormat_Layout) which writes to a container 'handlers' => array() _data/sites/pages.php
      'handlers' => 
      array (
        'VG9wVHdvTWVudTo_0' => 
        array (
          0 => 'Menu_Format_Layouts:RGVmYXVsdA',
        ),
      ),

VG9wVHdvTWVudTo = TopTwoMenu:
RGVmYXVsdA = Default (my plugin setting)

If a gadget is specified on the template - gpOutput::Get('Gadget','Menu_Format_Layouts');
Instead of putting new content in the "TopTwoMenu:" container, a new container.... is created, which is not shown on the page

Typesetter 5.2 preserves the container name and replaces the content and displays it on the page
Typesetter 5.3 doesn't do this ... is there something wrong!?

------------------
If you delete all handlers in the configuration file (_data/sites/pages.php), it works again, but it is not possible to change it.

**Comment by rifloom** [comment]
OK! resolved :)

include/tool Output.php function Get()

			$outKeys =array();
			if( !$outSet && isset($gpOutConf[$default]) ){
				$outKeys[] = trim($default . ':' . $arg, ':');
			}

Need to close line or delete  $outKeys =array();

**Comment by gtbu** [comment]
As far as I understand it, you enter the title of an already existing area under add New area, and the existing one is deleted and an identical one with the same title (and content : lorem ipsum..) is created : It is not asked whether it already exists.(i tested that with Typesetter 5.2 - ok - true - could be queried)
Typesetter 5.3 does not overwrite the existing area (tested) -
Is that the reported error?

**Comment by gtbu** [comment]
P.S. 2: I cheked Your solution and added $outKeys =array(); in the 5.2 -version (as in 5.3-version) - and the overwriting was over --->  as long as the area was not published (same in 5.3)

( $outKeys =array() should be there, because it is set to false before ! Php8 doesnt tolerate that )

As long as You hav not published the area, a draftp.php is generated parallel to page.php (and deleted if You publish the existing area ).

* In admin/content/extra.php line 149 is a function :::      public static function AreaExists     and line 204 ExtraExists  --- which should be modified  // 
* In edit.php line 1324 is a strange     $files = scandir($extrasFolder) or []; evtl. better :::    $files = scandir($extrasFolder , 1) ?: '[]';

**Comment by rifloom** [comment]
With the change described above, there is currently no problem with PHP8 ... No errors are given.
Of course, I haven't tested everything.

Tested in laragon for windows https://laragon.org/

$outKeys =array() 
overwrites a previously declared  $outKeys = $handlers[$container_id];
in 
Output.php function  Get($default='', $arg='')

and then  no gadget or extracontent is shown here (in handlers container)
$outKeys[] = trim($default . ':' . $arg, ':'); 
and thats is all :(

I am a hobbyist and not a professional, but mayby ....

			if( !$outSet && isset($gpOutConf[$default]) ){
				$outKeys =array();				
				$outKeys[] = trim($default . ':' . $arg, ':');
			}

or thear is  $outKeys = false;
mayby $outKeys = array(); 
and
if(empty($outKeys))
$outKeys = false;

I do not know :)

**Comment by gtbu** [comment]
1. I shifted the $outKeys =array();  into the existing if{....} - it is only deprecated (Automatic conversion of false to array is deprecated) 

2. The problem of overwriting existing areas with the same name is unsolved. I have no pronlems with editiong areas.....
but :
i cant find in pages.php a code with
 **'handlers' =>** 
  array (
    'RXh0cmE6Rm9vdGVyX0NvbA_0' => 
    array (
      0 => 'Extra:Lorem',
      1 => 'Extra:Footer_Column_1',
    ),
  ),
Do You use some tool ?

**Comment by gtbu** [comment]
1. At the top of this site You say : 'handlers' => array() in Typesetter (_data/sites/pages.php) . In my installation is no such code.

2. If You add a new area manually, You must pay attention , that an area with the same name does not alrerady exist. 
3. If such an area is published, the it overwrite the conten of the existing area with Lorem Ipsum.
Some templates and plugins have such Textareas - and before Typesetter 5.2 there was no autoregistration - the autors must give these areas a uniqe name

**Comment by rifloom** [comment]
I did a fresh install. If you go to change the layout http://typesetter-5.3-php8.test/Admin_Theme_Content/Edit/default?redir=Home
... I put different content (insert) in these areas, Footer Column  1, 2, 3
And the given lines appeared in the pages.php data file ...

 'handlers' => 
      array (
        'RXh0cmE6Rm9vdGVyX0NvbA_0' => 
        array (
          0 => 'Extra:Lorem',
          1 => 'Extra:Footer_Column_1',
        ),
        'RXh0cmE6Rm9vdGVyX0NvbA_1' => 
        array (
          0 => 'Extra:Header',
          1 => 'Extra:Footer_Column_2',
        ),
        'RXh0cmE6Rm9vdGVyX0NvbA_2' => 
        array (
          0 => 'Extra:Lorem',
          1 => 'Extra:Footer_Column_3',
        ),
      ),
      'hander_v' => '2', 

Strange that you don't have lines like that, hmm :o

**Comment by gtbu** [comment]
Yes ; but this code 
  'doctype' => '',
      'all_gadgets' => false,
      'template_mod' => 1684759325,
      'handlers' => 
      array (
        'W3RleHRdQWRtaW4tTGluay1BcmVhOg_0' => 
        array (
          0 => 'Extra:Footercol5',
          1 => '[text]Admin-Link-Area',
        ),
      ),
      'hander_v' => '2',
      'customizer_css' => true,

appers only of You insert another Textarea -  (Offered in  this case is a huge menu with everything. You can also choose  a menu - i dont know whether Mr. Krausz intended to to so. He left during Corona....)
First You should publish the areas.  I think it is better to add text  under extra content - but if You have time, You can overwork the bootstrap 4 and make  a helpfile. I have only limited time and bootstrap 5.2 or 5.3 and a theme is in work.
The other thing is the blocking of overwriting of existing areas. Both have priority.

**Comment by rifloom** [comment]
What is the 1 => '[text]Admin-Link-Area',

**Comment by gtbu** [comment]
I don't see much point in the possibility of being able to embed a GpExtra area in a text area. This creates hidden structures in the areas that are difficult to style.
CSS3, Jquery and Boootstrap offer sufficient alternatives.
As for the $outKeys =array(); concerns : Php7 does this automatically. 
The code is processed one after the other.
However, with ...OR []; it is possibly confused. ( use ...?? [] )
