### ISSUE TITLE
Upgrade Problems from 5.1

### ISSUE THREAD

**Issue by Im4GH** [gtbu/Typesetter-5.3-p8#4]
Is this Package only for a new clean Install or is there a "Best Pract" for upgrading from 5.1 to 5.3?

**Comment by gtbu** [comment]
The package is for a clean install.
If You want to update to my TP 5.3 b1 (only php8.0 ! - evtl. 8.1 ) 
A . First make a backup under tools and install Filezillla-portable (doesnt omit some filetypes and stabilizes the connection) at Your PC
B. Rename the gpconfig.php to gpconfig.old  and copy the new gpconfig.php there (ftp)
C. Rename the /include-directory to include.old and copy the 5.3-include directory parallel

Problems : Some templates and plugins of 5.1 may be so old and outdated that the new CMS will hang (_otherwise i would develop a core-update-plugin_)

* Safer is a process which first updates to my 5.1.1 (also in this git ; also the templates and addons (NOT the _data - directory!!!) or to my 5.2  (php7.3 or 7.4) - and then the templates and plugins
* If You still use php 5.6 or 7.2 then You should do all this with the github.cm/Typesetter - master.

**Comment by Im4GH** [comment]
Well, it works with the 1st Solution A-C without any Problems from 7.4 to 8.1 PHP and TS5.1 to your b1 :-)

**Comment by osopolar** [comment]
C. Copy Addon.ini
